FROM n8nio/n8n

ARG PSDB_ADDR
ARG PSDB_PORT
ARG PSDB_USER
ARG PSDB_PASS
ARG PSDB_DB

ENV DB_TYPE=mysqldb
ENV DB_MYSQLDB_HOST=$PSDB_ADDR
ENV DB_MYSQLDB_USER=$PSDB_USER
ENV DB_MYSQLDB_PASSWORD=$PSDB_PASS
ENV DB_MYSQLDB_DATABASE=$PSDB_DB

CMD ["n8n", "start"]
