FROM n8nio/n8n

ARG DATABASE_TYPE=mysql
ARG DATABASE_DB
ARG DATABASE_USER
ARG DATABASE_PASSWORD
ARG DATABASE_HOST

ARG GENERIC_TIMEZONE
ARG N8N_HOST
ARG N8N_PROTOCOL
ARG N8N_PORT
ARG WEBHOOK_TUNNEL_URL

ARG USERNAME
ARG PASSWORD

ENV DB_TYPE=$DATABASE_TYPE
ENV DB_MYSQLDB_DATABASE=$DATABASE_DB
ENV DB_MYSQLDB_HOST=$DATABASE_HOST
ENV DB_MYSQLDB_PORT=3306
ENV DB_MYSQLDB_USER=$DATABASE_USER
ENV DB_MYSQLDB_PASSWORD=$DATABASE_PASSWORD

ENV GENERIC_TIMEZONE=$GENERIC_TIMEZONE
ENV N8N_HOST=$N8N_HOST
ENV N8N_PROTOCOL=$N8N_PROTOCOL
ENV N8N_PORT=$N8N_PORT
ENV WEBHOOK_TUNNEL_URL=$WEBHOOK_TUNNEL_URL

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=$USERNAME
ENV N8N_BASIC_AUTH_PASSWORD=$PASSWORD

CMD ["n8n", "start"]
